services:
  go_db:
    container_name: booksdb
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-app:
    container_name: books-api
    image: go-books-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      go_db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pgdata: {}